//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitDataSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnBoard()
        {
            this.SpecialOnBoards = new HashSet<SpecialOnBoard>();
        }
    
        public int OnBoardID { get; set; }
        public int LocationID { get; set; }
        public int BusID { get; set; }
        public System.DateTime OnBoardTimeStamp { get; set; }
        public Nullable<byte> YouthOnBoard { get; set; }
        public Nullable<byte> AdultOnBoard { get; set; }
        public Nullable<byte> SeniorOnBoard { get; set; }
        public Nullable<byte> HandicapOnBoard { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialOnBoard> SpecialOnBoards { get; set; }
    }
}
