//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitDataSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialOnBoard
    {
        public int SpecialID { get; set; }
        public int OnBoardID { get; set; }
        public string SpecialTag { get; set; }
        public Nullable<byte> SpecialCount { get; set; }
    
        public virtual OnBoard OnBoard { get; set; }
    }
}
