//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitDataSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransitDataEntities : DbContext
    {
        public TransitDataEntities()
            : base("name=TransitDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<OnBoard> OnBoards { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<SpecialOnBoard> SpecialOnBoards { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
    }
}
